### PR TITLE
Explicitly close div

### PR DESCRIPTION
**Pull request by christianwach**
The layout of some HTML5 themes breaks because of the self-closing `<div class="clear"/>`. Explcitly closing this fixes the problem.

### CODE REVIEW

**Comment by solhuebner** [comment]
:+1:

**Comment by imath** [comment]
Ok thanks, i'll include for next release which should happen as soon as WordPress 4.2 will be released.

**Comment by christianwach** [comment]
Thanks @imath

**Comment by imath** [comment]
Sorry @christianwach i missed this for 1.4.0, but it will be there for 1.4.1. Thanks a lot for your contribution.

see https://github.com/imath/rendez-vous/commit/8907dad78da3426468fd7325cb85da78f55031b4

**Comment by christianwach** [comment]
Good news, thank you.

**Pull request closed without merging**
